// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for CreateQuestionRequestDifficulty.
const (
	CreateQuestionRequestDifficultyEasy   CreateQuestionRequestDifficulty = "easy"
	CreateQuestionRequestDifficultyHard   CreateQuestionRequestDifficulty = "hard"
	CreateQuestionRequestDifficultyMedium CreateQuestionRequestDifficulty = "medium"
)

// Valid indicates whether the value is a known member of the CreateQuestionRequestDifficulty enum.
func (e CreateQuestionRequestDifficulty) Valid() bool {
	switch e {
	case CreateQuestionRequestDifficultyEasy:
		return true
	case CreateQuestionRequestDifficultyHard:
		return true
	case CreateQuestionRequestDifficultyMedium:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	Degraded HealthResponseStatus = "degraded"
	Ok       HealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Degraded:
		return true
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for QuestionDetailResponseDifficulty.
const (
	QuestionDetailResponseDifficultyEasy   QuestionDetailResponseDifficulty = "easy"
	QuestionDetailResponseDifficultyHard   QuestionDetailResponseDifficulty = "hard"
	QuestionDetailResponseDifficultyMedium QuestionDetailResponseDifficulty = "medium"
)

// Valid indicates whether the value is a known member of the QuestionDetailResponseDifficulty enum.
func (e QuestionDetailResponseDifficulty) Valid() bool {
	switch e {
	case QuestionDetailResponseDifficultyEasy:
		return true
	case QuestionDetailResponseDifficultyHard:
		return true
	case QuestionDetailResponseDifficultyMedium:
		return true
	default:
		return false
	}
}

// Defines values for RegisterRequestRole.
const (
	RegisterRequestRoleContributor RegisterRequestRole = "contributor"
	RegisterRequestRoleStudent     RegisterRequestRole = "student"
)

// Valid indicates whether the value is a known member of the RegisterRequestRole enum.
func (e RegisterRequestRole) Valid() bool {
	switch e {
	case RegisterRequestRoleContributor:
		return true
	case RegisterRequestRoleStudent:
		return true
	default:
		return false
	}
}

// Defines values for UpdateQuestionRequestDifficulty.
const (
	UpdateQuestionRequestDifficultyEasy   UpdateQuestionRequestDifficulty = "easy"
	UpdateQuestionRequestDifficultyHard   UpdateQuestionRequestDifficulty = "hard"
	UpdateQuestionRequestDifficultyMedium UpdateQuestionRequestDifficulty = "medium"
)

// Valid indicates whether the value is a known member of the UpdateQuestionRequestDifficulty enum.
func (e UpdateQuestionRequestDifficulty) Valid() bool {
	switch e {
	case UpdateQuestionRequestDifficultyEasy:
		return true
	case UpdateQuestionRequestDifficultyHard:
		return true
	case UpdateQuestionRequestDifficultyMedium:
		return true
	default:
		return false
	}
}

// Defines values for UserResponseRole.
const (
	UserResponseRoleAdmin       UserResponseRole = "admin"
	UserResponseRoleContributor UserResponseRole = "contributor"
	UserResponseRoleStudent     UserResponseRole = "student"
)

// Valid indicates whether the value is a known member of the UserResponseRole enum.
func (e UserResponseRole) Valid() bool {
	switch e {
	case UserResponseRoleAdmin:
		return true
	case UserResponseRoleContributor:
		return true
	case UserResponseRoleStudent:
		return true
	default:
		return false
	}
}

// Defines values for UserResponseStatus.
const (
	Active    UserResponseStatus = "active"
	Inactive  UserResponseStatus = "inactive"
	Pending   UserResponseStatus = "pending"
	Suspended UserResponseStatus = "suspended"
)

// Valid indicates whether the value is a known member of the UserResponseStatus enum.
func (e UserResponseStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Inactive:
		return true
	case Pending:
		return true
	case Suspended:
		return true
	default:
		return false
	}
}

// Defines values for GetQuestionsParamsDifficulty.
const (
	GetQuestionsParamsDifficultyEasy   GetQuestionsParamsDifficulty = "easy"
	GetQuestionsParamsDifficultyHard   GetQuestionsParamsDifficulty = "hard"
	GetQuestionsParamsDifficultyMedium GetQuestionsParamsDifficulty = "medium"
)

// Valid indicates whether the value is a known member of the GetQuestionsParamsDifficulty enum.
func (e GetQuestionsParamsDifficulty) Valid() bool {
	switch e {
	case GetQuestionsParamsDifficultyEasy:
		return true
	case GetQuestionsParamsDifficultyHard:
		return true
	case GetQuestionsParamsDifficultyMedium:
		return true
	default:
		return false
	}
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	AccessToken  string       `json:"access_token"`
	RefreshToken string       `json:"refresh_token"`
	User         UserResponse `json:"user"`
}

// CreateQuestionRequest defines model for CreateQuestionRequest.
type CreateQuestionRequest struct {
	Difficulty  CreateQuestionRequestDifficulty `json:"difficulty"`
	Explanation *string                         `json:"explanation,omitempty"`
	Options     []QuestionOptionInput           `json:"options"`
	Text        string                          `json:"text"`
	TopicId     openapi_types.UUID              `json:"topic_id"`
}

// CreateQuestionRequestDifficulty defines model for CreateQuestionRequest.Difficulty.
type CreateQuestionRequestDifficulty string

// CreateTopicRequest defines model for CreateTopicRequest.
type CreateTopicRequest struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		Code    string `json:"code"`
		Details *[]struct {
			Field *string `json:"field,omitempty"`
			Issue *string `json:"issue,omitempty"`
		} `json:"details,omitempty"`
		Message string `json:"message"`
	} `json:"error"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status    HealthResponseStatus `json:"status"`
	Timestamp time.Time            `json:"timestamp"`
	Version   *string              `json:"version,omitempty"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// LogoutRequest defines model for LogoutRequest.
type LogoutRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// MessageResponse defines model for MessageResponse.
type MessageResponse struct {
	Message string `json:"message"`
}

// QuestionDetailResponse defines model for QuestionDetailResponse.
type QuestionDetailResponse struct {
	ContributorId openapi_types.UUID               `json:"contributor_id"`
	CreatedAt     time.Time                        `json:"created_at"`
	Difficulty    QuestionDetailResponseDifficulty `json:"difficulty"`
	Explanation   *string                          `json:"explanation,omitempty"`
	Id            openapi_types.UUID               `json:"id"`
	Options       []QuestionOptionResponse         `json:"options"`
	Text          string                           `json:"text"`
	TopicId       openapi_types.UUID               `json:"topic_id"`
	UpdatedAt     time.Time                        `json:"updated_at"`
}

// QuestionDetailResponseDifficulty defines model for QuestionDetailResponse.Difficulty.
type QuestionDetailResponseDifficulty string

// QuestionListResponse defines model for QuestionListResponse.
type QuestionListResponse struct {
	Data  []QuestionDetailResponse `json:"data"`
	Limit int                      `json:"limit"`
	Page  int                      `json:"page"`
	Total int                      `json:"total"`
}

// QuestionOptionInput defines model for QuestionOptionInput.
type QuestionOptionInput struct {
	IsCorrect bool   `json:"is_correct"`
	Label     string `json:"label"`
	Text      string `json:"text"`
}

// QuestionOptionResponse defines model for QuestionOptionResponse.
type QuestionOptionResponse struct {
	Id        openapi_types.UUID `json:"id"`
	IsCorrect bool               `json:"is_correct"`
	Label     string             `json:"label"`
	Text      string             `json:"text"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    openapi_types.Email `json:"email"`
	Name     string              `json:"name"`
	Password string              `json:"password"`
	Role     RegisterRequestRole `json:"role"`
}

// RegisterRequestRole defines model for RegisterRequest.Role.
type RegisterRequestRole string

// TopicResponse defines model for TopicResponse.
type TopicResponse struct {
	CreatedAt   time.Time          `json:"created_at"`
	Description *string            `json:"description,omitempty"`
	Id          openapi_types.UUID `json:"id"`
	Name        string             `json:"name"`
}

// UpdateQuestionRequest defines model for UpdateQuestionRequest.
type UpdateQuestionRequest struct {
	Difficulty  *UpdateQuestionRequestDifficulty `json:"difficulty,omitempty"`
	Explanation *string                          `json:"explanation,omitempty"`
	Options     *[]QuestionOptionInput           `json:"options,omitempty"`
	Text        *string                          `json:"text,omitempty"`
	TopicId     *openapi_types.UUID              `json:"topic_id,omitempty"`
}

// UpdateQuestionRequestDifficulty defines model for UpdateQuestionRequest.Difficulty.
type UpdateQuestionRequestDifficulty string

// UpdateTopicRequest defines model for UpdateTopicRequest.
type UpdateTopicRequest struct {
	Description *string `json:"description,omitempty"`
	Name        *string `json:"name,omitempty"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	CreatedAt time.Time           `json:"created_at"`
	Email     openapi_types.Email `json:"email"`
	Id        openapi_types.UUID  `json:"id"`
	Name      string              `json:"name"`
	Role      UserResponseRole    `json:"role"`
	Status    UserResponseStatus  `json:"status"`
}

// UserResponseRole defines model for UserResponse.Role.
type UserResponseRole string

// UserResponseStatus defines model for UserResponse.Status.
type UserResponseStatus string

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// GetQuestionsParams defines parameters for GetQuestions.
type GetQuestionsParams struct {
	Search     *string                       `form:"search,omitempty" json:"search,omitempty"`
	TopicId    *openapi_types.UUID           `form:"topic_id,omitempty" json:"topic_id,omitempty"`
	Difficulty *GetQuestionsParamsDifficulty `form:"difficulty,omitempty" json:"difficulty,omitempty"`
	Page       *int                          `form:"page,omitempty" json:"page,omitempty"`
	Limit      *int                          `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetQuestionsParamsDifficulty defines parameters for GetQuestions.
type GetQuestionsParamsDifficulty string

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody = LoginRequest

// PostAuthLogoutJSONRequestBody defines body for PostAuthLogout for application/json ContentType.
type PostAuthLogoutJSONRequestBody = LogoutRequest

// PostAuthRefreshJSONRequestBody defines body for PostAuthRefresh for application/json ContentType.
type PostAuthRefreshJSONRequestBody = RefreshRequest

// PostAuthRegisterJSONRequestBody defines body for PostAuthRegister for application/json ContentType.
type PostAuthRegisterJSONRequestBody = RegisterRequest

// PostQuestionsJSONRequestBody defines body for PostQuestions for application/json ContentType.
type PostQuestionsJSONRequestBody = CreateQuestionRequest

// PatchQuestionsQuestionIdJSONRequestBody defines body for PatchQuestionsQuestionId for application/json ContentType.
type PatchQuestionsQuestionIdJSONRequestBody = UpdateQuestionRequest

// PostTopicsJSONRequestBody defines body for PostTopics for application/json ContentType.
type PostTopicsJSONRequestBody = CreateTopicRequest

// PatchTopicsTopicIdJSONRequestBody defines body for PatchTopicsTopicId for application/json ContentType.
type PatchTopicsTopicIdJSONRequestBody = UpdateTopicRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Authenticate and receive tokens
	// (POST /auth/login)
	PostAuthLogin(w http.ResponseWriter, r *http.Request)
	// Invalidate the current refresh token
	// (POST /auth/logout)
	PostAuthLogout(w http.ResponseWriter, r *http.Request)
	// Get the current authenticated user's profile
	// (GET /auth/me)
	GetAuthMe(w http.ResponseWriter, r *http.Request)
	// Rotate refresh token and get a new access token
	// (POST /auth/refresh)
	PostAuthRefresh(w http.ResponseWriter, r *http.Request)
	// Register a new user
	// (POST /auth/register)
	PostAuthRegister(w http.ResponseWriter, r *http.Request)
	// Health check
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// List questions (contributor/admin)
	// (GET /questions)
	GetQuestions(w http.ResponseWriter, r *http.Request, params GetQuestionsParams)
	// Create a question (contributor only)
	// (POST /questions)
	PostQuestions(w http.ResponseWriter, r *http.Request)
	// Delete a question (own only; blocked if in published test)
	// (DELETE /questions/{questionId})
	DeleteQuestionsQuestionId(w http.ResponseWriter, r *http.Request, questionId openapi_types.UUID)
	// Get question detail
	// (GET /questions/{questionId})
	GetQuestionsQuestionId(w http.ResponseWriter, r *http.Request, questionId openapi_types.UUID)
	// Update a question (own only for contributor, any for admin)
	// (PATCH /questions/{questionId})
	PatchQuestionsQuestionId(w http.ResponseWriter, r *http.Request, questionId openapi_types.UUID)
	// List all topics
	// (GET /topics)
	GetTopics(w http.ResponseWriter, r *http.Request)
	// Create a topic (admin only)
	// (POST /topics)
	PostTopics(w http.ResponseWriter, r *http.Request)
	// Delete a topic (admin only)
	// (DELETE /topics/{topicId})
	DeleteTopicsTopicId(w http.ResponseWriter, r *http.Request, topicId openapi_types.UUID)
	// Update a topic (admin only)
	// (PATCH /topics/{topicId})
	PatchTopicsTopicId(w http.ResponseWriter, r *http.Request, topicId openapi_types.UUID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Authenticate and receive tokens
// (POST /auth/login)
func (_ Unimplemented) PostAuthLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Invalidate the current refresh token
// (POST /auth/logout)
func (_ Unimplemented) PostAuthLogout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get the current authenticated user's profile
// (GET /auth/me)
func (_ Unimplemented) GetAuthMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Rotate refresh token and get a new access token
// (POST /auth/refresh)
func (_ Unimplemented) PostAuthRefresh(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Register a new user
// (POST /auth/register)
func (_ Unimplemented) PostAuthRegister(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health check
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List questions (contributor/admin)
// (GET /questions)
func (_ Unimplemented) GetQuestions(w http.ResponseWriter, r *http.Request, params GetQuestionsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a question (contributor only)
// (POST /questions)
func (_ Unimplemented) PostQuestions(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a question (own only; blocked if in published test)
// (DELETE /questions/{questionId})
func (_ Unimplemented) DeleteQuestionsQuestionId(w http.ResponseWriter, r *http.Request, questionId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get question detail
// (GET /questions/{questionId})
func (_ Unimplemented) GetQuestionsQuestionId(w http.ResponseWriter, r *http.Request, questionId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a question (own only for contributor, any for admin)
// (PATCH /questions/{questionId})
func (_ Unimplemented) PatchQuestionsQuestionId(w http.ResponseWriter, r *http.Request, questionId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all topics
// (GET /topics)
func (_ Unimplemented) GetTopics(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a topic (admin only)
// (POST /topics)
func (_ Unimplemented) PostTopics(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a topic (admin only)
// (DELETE /topics/{topicId})
func (_ Unimplemented) DeleteTopicsTopicId(w http.ResponseWriter, r *http.Request, topicId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a topic (admin only)
// (PATCH /topics/{topicId})
func (_ Unimplemented) PatchTopicsTopicId(w http.ResponseWriter, r *http.Request, topicId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostAuthLogin operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthLogout operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogout(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthLogout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthMe operation middleware
func (siw *ServerInterfaceWrapper) GetAuthMe(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthRefresh operation middleware
func (siw *ServerInterfaceWrapper) PostAuthRefresh(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthRefresh(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthRegister operation middleware
func (siw *ServerInterfaceWrapper) PostAuthRegister(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthRegister(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetQuestions operation middleware
func (siw *ServerInterfaceWrapper) GetQuestions(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetQuestionsParams

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", r.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "search"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "topic_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "topic_id", r.URL.Query(), &params.TopicId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "topic_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "topic_id", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "difficulty" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "difficulty", r.URL.Query(), &params.Difficulty, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "difficulty"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "difficulty", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetQuestions(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostQuestions operation middleware
func (siw *ServerInterfaceWrapper) PostQuestions(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostQuestions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteQuestionsQuestionId operation middleware
func (siw *ServerInterfaceWrapper) DeleteQuestionsQuestionId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "questionId" -------------
	var questionId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "questionId", chi.URLParam(r, "questionId"), &questionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "questionId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteQuestionsQuestionId(w, r, questionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetQuestionsQuestionId operation middleware
func (siw *ServerInterfaceWrapper) GetQuestionsQuestionId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "questionId" -------------
	var questionId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "questionId", chi.URLParam(r, "questionId"), &questionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "questionId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetQuestionsQuestionId(w, r, questionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchQuestionsQuestionId operation middleware
func (siw *ServerInterfaceWrapper) PatchQuestionsQuestionId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "questionId" -------------
	var questionId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "questionId", chi.URLParam(r, "questionId"), &questionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "questionId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchQuestionsQuestionId(w, r, questionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTopics operation middleware
func (siw *ServerInterfaceWrapper) GetTopics(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTopics(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostTopics operation middleware
func (siw *ServerInterfaceWrapper) PostTopics(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostTopics(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTopicsTopicId operation middleware
func (siw *ServerInterfaceWrapper) DeleteTopicsTopicId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "topicId" -------------
	var topicId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "topicId", chi.URLParam(r, "topicId"), &topicId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "topicId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTopicsTopicId(w, r, topicId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchTopicsTopicId operation middleware
func (siw *ServerInterfaceWrapper) PatchTopicsTopicId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "topicId" -------------
	var topicId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "topicId", chi.URLParam(r, "topicId"), &topicId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "topicId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchTopicsTopicId(w, r, topicId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.PostAuthLogin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.PostAuthLogout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/me", wrapper.GetAuthMe)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/refresh", wrapper.PostAuthRefresh)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/register", wrapper.PostAuthRegister)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/questions", wrapper.GetQuestions)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/questions", wrapper.PostQuestions)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/questions/{questionId}", wrapper.DeleteQuestionsQuestionId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/questions/{questionId}", wrapper.GetQuestionsQuestionId)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/questions/{questionId}", wrapper.PatchQuestionsQuestionId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/topics", wrapper.GetTopics)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/topics", wrapper.PostTopics)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/topics/{topicId}", wrapper.DeleteTopicsTopicId)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/topics/{topicId}", wrapper.PatchTopicsTopicId)
	})

	return r
}

type PostAuthLoginRequestObject struct {
	Body *PostAuthLoginJSONRequestBody
}

type PostAuthLoginResponseObject interface {
	VisitPostAuthLoginResponse(w http.ResponseWriter) error
}

type PostAuthLogin200JSONResponse AuthResponse

func (response PostAuthLogin200JSONResponse) VisitPostAuthLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostAuthLogin401JSONResponse ErrorResponse

func (response PostAuthLogin401JSONResponse) VisitPostAuthLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PostAuthLogin422JSONResponse ErrorResponse

func (response PostAuthLogin422JSONResponse) VisitPostAuthLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type PostAuthLogoutRequestObject struct {
	Body *PostAuthLogoutJSONRequestBody
}

type PostAuthLogoutResponseObject interface {
	VisitPostAuthLogoutResponse(w http.ResponseWriter) error
}

type PostAuthLogout200JSONResponse MessageResponse

func (response PostAuthLogout200JSONResponse) VisitPostAuthLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostAuthLogout401JSONResponse ErrorResponse

func (response PostAuthLogout401JSONResponse) VisitPostAuthLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetAuthMeRequestObject struct {
}

type GetAuthMeResponseObject interface {
	VisitGetAuthMeResponse(w http.ResponseWriter) error
}

type GetAuthMe200JSONResponse UserResponse

func (response GetAuthMe200JSONResponse) VisitGetAuthMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAuthMe401JSONResponse ErrorResponse

func (response GetAuthMe401JSONResponse) VisitGetAuthMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PostAuthRefreshRequestObject struct {
	Body *PostAuthRefreshJSONRequestBody
}

type PostAuthRefreshResponseObject interface {
	VisitPostAuthRefreshResponse(w http.ResponseWriter) error
}

type PostAuthRefresh200JSONResponse AuthResponse

func (response PostAuthRefresh200JSONResponse) VisitPostAuthRefreshResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostAuthRefresh401JSONResponse ErrorResponse

func (response PostAuthRefresh401JSONResponse) VisitPostAuthRefreshResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PostAuthRegisterRequestObject struct {
	Body *PostAuthRegisterJSONRequestBody
}

type PostAuthRegisterResponseObject interface {
	VisitPostAuthRegisterResponse(w http.ResponseWriter) error
}

type PostAuthRegister201JSONResponse AuthResponse

func (response PostAuthRegister201JSONResponse) VisitPostAuthRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type PostAuthRegister409JSONResponse ErrorResponse

func (response PostAuthRegister409JSONResponse) VisitPostAuthRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type PostAuthRegister422JSONResponse ErrorResponse

func (response PostAuthRegister422JSONResponse) VisitPostAuthRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse HealthResponse

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetQuestionsRequestObject struct {
	Params GetQuestionsParams
}

type GetQuestionsResponseObject interface {
	VisitGetQuestionsResponse(w http.ResponseWriter) error
}

type GetQuestions200JSONResponse QuestionListResponse

func (response GetQuestions200JSONResponse) VisitGetQuestionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetQuestions401JSONResponse ErrorResponse

func (response GetQuestions401JSONResponse) VisitGetQuestionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetQuestions403JSONResponse ErrorResponse

func (response GetQuestions403JSONResponse) VisitGetQuestionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type PostQuestionsRequestObject struct {
	Body *PostQuestionsJSONRequestBody
}

type PostQuestionsResponseObject interface {
	VisitPostQuestionsResponse(w http.ResponseWriter) error
}

type PostQuestions201JSONResponse QuestionDetailResponse

func (response PostQuestions201JSONResponse) VisitPostQuestionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type PostQuestions401JSONResponse ErrorResponse

func (response PostQuestions401JSONResponse) VisitPostQuestionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PostQuestions403JSONResponse ErrorResponse

func (response PostQuestions403JSONResponse) VisitPostQuestionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type PostQuestions422JSONResponse ErrorResponse

func (response PostQuestions422JSONResponse) VisitPostQuestionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteQuestionsQuestionIdRequestObject struct {
	QuestionId openapi_types.UUID `json:"questionId"`
}

type DeleteQuestionsQuestionIdResponseObject interface {
	VisitDeleteQuestionsQuestionIdResponse(w http.ResponseWriter) error
}

type DeleteQuestionsQuestionId200JSONResponse MessageResponse

func (response DeleteQuestionsQuestionId200JSONResponse) VisitDeleteQuestionsQuestionIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteQuestionsQuestionId401JSONResponse ErrorResponse

func (response DeleteQuestionsQuestionId401JSONResponse) VisitDeleteQuestionsQuestionIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteQuestionsQuestionId403JSONResponse ErrorResponse

func (response DeleteQuestionsQuestionId403JSONResponse) VisitDeleteQuestionsQuestionIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteQuestionsQuestionId404JSONResponse ErrorResponse

func (response DeleteQuestionsQuestionId404JSONResponse) VisitDeleteQuestionsQuestionIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteQuestionsQuestionId409JSONResponse ErrorResponse

func (response DeleteQuestionsQuestionId409JSONResponse) VisitDeleteQuestionsQuestionIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type GetQuestionsQuestionIdRequestObject struct {
	QuestionId openapi_types.UUID `json:"questionId"`
}

type GetQuestionsQuestionIdResponseObject interface {
	VisitGetQuestionsQuestionIdResponse(w http.ResponseWriter) error
}

type GetQuestionsQuestionId200JSONResponse QuestionDetailResponse

func (response GetQuestionsQuestionId200JSONResponse) VisitGetQuestionsQuestionIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetQuestionsQuestionId401JSONResponse ErrorResponse

func (response GetQuestionsQuestionId401JSONResponse) VisitGetQuestionsQuestionIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetQuestionsQuestionId403JSONResponse ErrorResponse

func (response GetQuestionsQuestionId403JSONResponse) VisitGetQuestionsQuestionIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetQuestionsQuestionId404JSONResponse ErrorResponse

func (response GetQuestionsQuestionId404JSONResponse) VisitGetQuestionsQuestionIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PatchQuestionsQuestionIdRequestObject struct {
	QuestionId openapi_types.UUID `json:"questionId"`
	Body       *PatchQuestionsQuestionIdJSONRequestBody
}

type PatchQuestionsQuestionIdResponseObject interface {
	VisitPatchQuestionsQuestionIdResponse(w http.ResponseWriter) error
}

type PatchQuestionsQuestionId200JSONResponse QuestionDetailResponse

func (response PatchQuestionsQuestionId200JSONResponse) VisitPatchQuestionsQuestionIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PatchQuestionsQuestionId401JSONResponse ErrorResponse

func (response PatchQuestionsQuestionId401JSONResponse) VisitPatchQuestionsQuestionIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PatchQuestionsQuestionId403JSONResponse ErrorResponse

func (response PatchQuestionsQuestionId403JSONResponse) VisitPatchQuestionsQuestionIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type PatchQuestionsQuestionId404JSONResponse ErrorResponse

func (response PatchQuestionsQuestionId404JSONResponse) VisitPatchQuestionsQuestionIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PatchQuestionsQuestionId422JSONResponse ErrorResponse

func (response PatchQuestionsQuestionId422JSONResponse) VisitPatchQuestionsQuestionIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type GetTopicsRequestObject struct {
}

type GetTopicsResponseObject interface {
	VisitGetTopicsResponse(w http.ResponseWriter) error
}

type GetTopics200JSONResponse struct {
	Data []TopicResponse `json:"data"`
}

func (response GetTopics200JSONResponse) VisitGetTopicsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostTopicsRequestObject struct {
	Body *PostTopicsJSONRequestBody
}

type PostTopicsResponseObject interface {
	VisitPostTopicsResponse(w http.ResponseWriter) error
}

type PostTopics201JSONResponse TopicResponse

func (response PostTopics201JSONResponse) VisitPostTopicsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type PostTopics401JSONResponse ErrorResponse

func (response PostTopics401JSONResponse) VisitPostTopicsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PostTopics403JSONResponse ErrorResponse

func (response PostTopics403JSONResponse) VisitPostTopicsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type PostTopics422JSONResponse ErrorResponse

func (response PostTopics422JSONResponse) VisitPostTopicsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteTopicsTopicIdRequestObject struct {
	TopicId openapi_types.UUID `json:"topicId"`
}

type DeleteTopicsTopicIdResponseObject interface {
	VisitDeleteTopicsTopicIdResponse(w http.ResponseWriter) error
}

type DeleteTopicsTopicId200JSONResponse MessageResponse

func (response DeleteTopicsTopicId200JSONResponse) VisitDeleteTopicsTopicIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteTopicsTopicId401JSONResponse ErrorResponse

func (response DeleteTopicsTopicId401JSONResponse) VisitDeleteTopicsTopicIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteTopicsTopicId403JSONResponse ErrorResponse

func (response DeleteTopicsTopicId403JSONResponse) VisitDeleteTopicsTopicIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteTopicsTopicId404JSONResponse ErrorResponse

func (response DeleteTopicsTopicId404JSONResponse) VisitDeleteTopicsTopicIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteTopicsTopicId409JSONResponse ErrorResponse

func (response DeleteTopicsTopicId409JSONResponse) VisitDeleteTopicsTopicIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type PatchTopicsTopicIdRequestObject struct {
	TopicId openapi_types.UUID `json:"topicId"`
	Body    *PatchTopicsTopicIdJSONRequestBody
}

type PatchTopicsTopicIdResponseObject interface {
	VisitPatchTopicsTopicIdResponse(w http.ResponseWriter) error
}

type PatchTopicsTopicId200JSONResponse TopicResponse

func (response PatchTopicsTopicId200JSONResponse) VisitPatchTopicsTopicIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PatchTopicsTopicId401JSONResponse ErrorResponse

func (response PatchTopicsTopicId401JSONResponse) VisitPatchTopicsTopicIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PatchTopicsTopicId403JSONResponse ErrorResponse

func (response PatchTopicsTopicId403JSONResponse) VisitPatchTopicsTopicIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type PatchTopicsTopicId404JSONResponse ErrorResponse

func (response PatchTopicsTopicId404JSONResponse) VisitPatchTopicsTopicIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PatchTopicsTopicId409JSONResponse ErrorResponse

func (response PatchTopicsTopicId409JSONResponse) VisitPatchTopicsTopicIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type PatchTopicsTopicId422JSONResponse ErrorResponse

func (response PatchTopicsTopicId422JSONResponse) VisitPatchTopicsTopicIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Authenticate and receive tokens
	// (POST /auth/login)
	PostAuthLogin(ctx context.Context, request PostAuthLoginRequestObject) (PostAuthLoginResponseObject, error)
	// Invalidate the current refresh token
	// (POST /auth/logout)
	PostAuthLogout(ctx context.Context, request PostAuthLogoutRequestObject) (PostAuthLogoutResponseObject, error)
	// Get the current authenticated user's profile
	// (GET /auth/me)
	GetAuthMe(ctx context.Context, request GetAuthMeRequestObject) (GetAuthMeResponseObject, error)
	// Rotate refresh token and get a new access token
	// (POST /auth/refresh)
	PostAuthRefresh(ctx context.Context, request PostAuthRefreshRequestObject) (PostAuthRefreshResponseObject, error)
	// Register a new user
	// (POST /auth/register)
	PostAuthRegister(ctx context.Context, request PostAuthRegisterRequestObject) (PostAuthRegisterResponseObject, error)
	// Health check
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// List questions (contributor/admin)
	// (GET /questions)
	GetQuestions(ctx context.Context, request GetQuestionsRequestObject) (GetQuestionsResponseObject, error)
	// Create a question (contributor only)
	// (POST /questions)
	PostQuestions(ctx context.Context, request PostQuestionsRequestObject) (PostQuestionsResponseObject, error)
	// Delete a question (own only; blocked if in published test)
	// (DELETE /questions/{questionId})
	DeleteQuestionsQuestionId(ctx context.Context, request DeleteQuestionsQuestionIdRequestObject) (DeleteQuestionsQuestionIdResponseObject, error)
	// Get question detail
	// (GET /questions/{questionId})
	GetQuestionsQuestionId(ctx context.Context, request GetQuestionsQuestionIdRequestObject) (GetQuestionsQuestionIdResponseObject, error)
	// Update a question (own only for contributor, any for admin)
	// (PATCH /questions/{questionId})
	PatchQuestionsQuestionId(ctx context.Context, request PatchQuestionsQuestionIdRequestObject) (PatchQuestionsQuestionIdResponseObject, error)
	// List all topics
	// (GET /topics)
	GetTopics(ctx context.Context, request GetTopicsRequestObject) (GetTopicsResponseObject, error)
	// Create a topic (admin only)
	// (POST /topics)
	PostTopics(ctx context.Context, request PostTopicsRequestObject) (PostTopicsResponseObject, error)
	// Delete a topic (admin only)
	// (DELETE /topics/{topicId})
	DeleteTopicsTopicId(ctx context.Context, request DeleteTopicsTopicIdRequestObject) (DeleteTopicsTopicIdResponseObject, error)
	// Update a topic (admin only)
	// (PATCH /topics/{topicId})
	PatchTopicsTopicId(ctx context.Context, request PatchTopicsTopicIdRequestObject) (PatchTopicsTopicIdResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// PostAuthLogin operation middleware
func (sh *strictHandler) PostAuthLogin(w http.ResponseWriter, r *http.Request) {
	var request PostAuthLoginRequestObject

	var body PostAuthLoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostAuthLogin(ctx, request.(PostAuthLoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAuthLogin")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostAuthLoginResponseObject); ok {
		if err := validResponse.VisitPostAuthLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostAuthLogout operation middleware
func (sh *strictHandler) PostAuthLogout(w http.ResponseWriter, r *http.Request) {
	var request PostAuthLogoutRequestObject

	var body PostAuthLogoutJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostAuthLogout(ctx, request.(PostAuthLogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAuthLogout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostAuthLogoutResponseObject); ok {
		if err := validResponse.VisitPostAuthLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAuthMe operation middleware
func (sh *strictHandler) GetAuthMe(w http.ResponseWriter, r *http.Request) {
	var request GetAuthMeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAuthMe(ctx, request.(GetAuthMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAuthMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAuthMeResponseObject); ok {
		if err := validResponse.VisitGetAuthMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostAuthRefresh operation middleware
func (sh *strictHandler) PostAuthRefresh(w http.ResponseWriter, r *http.Request) {
	var request PostAuthRefreshRequestObject

	var body PostAuthRefreshJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostAuthRefresh(ctx, request.(PostAuthRefreshRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAuthRefresh")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostAuthRefreshResponseObject); ok {
		if err := validResponse.VisitPostAuthRefreshResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostAuthRegister operation middleware
func (sh *strictHandler) PostAuthRegister(w http.ResponseWriter, r *http.Request) {
	var request PostAuthRegisterRequestObject

	var body PostAuthRegisterJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostAuthRegister(ctx, request.(PostAuthRegisterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAuthRegister")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostAuthRegisterResponseObject); ok {
		if err := validResponse.VisitPostAuthRegisterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetQuestions operation middleware
func (sh *strictHandler) GetQuestions(w http.ResponseWriter, r *http.Request, params GetQuestionsParams) {
	var request GetQuestionsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetQuestions(ctx, request.(GetQuestionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetQuestions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetQuestionsResponseObject); ok {
		if err := validResponse.VisitGetQuestionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostQuestions operation middleware
func (sh *strictHandler) PostQuestions(w http.ResponseWriter, r *http.Request) {
	var request PostQuestionsRequestObject

	var body PostQuestionsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostQuestions(ctx, request.(PostQuestionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostQuestions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostQuestionsResponseObject); ok {
		if err := validResponse.VisitPostQuestionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteQuestionsQuestionId operation middleware
func (sh *strictHandler) DeleteQuestionsQuestionId(w http.ResponseWriter, r *http.Request, questionId openapi_types.UUID) {
	var request DeleteQuestionsQuestionIdRequestObject

	request.QuestionId = questionId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteQuestionsQuestionId(ctx, request.(DeleteQuestionsQuestionIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteQuestionsQuestionId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteQuestionsQuestionIdResponseObject); ok {
		if err := validResponse.VisitDeleteQuestionsQuestionIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetQuestionsQuestionId operation middleware
func (sh *strictHandler) GetQuestionsQuestionId(w http.ResponseWriter, r *http.Request, questionId openapi_types.UUID) {
	var request GetQuestionsQuestionIdRequestObject

	request.QuestionId = questionId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetQuestionsQuestionId(ctx, request.(GetQuestionsQuestionIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetQuestionsQuestionId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetQuestionsQuestionIdResponseObject); ok {
		if err := validResponse.VisitGetQuestionsQuestionIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PatchQuestionsQuestionId operation middleware
func (sh *strictHandler) PatchQuestionsQuestionId(w http.ResponseWriter, r *http.Request, questionId openapi_types.UUID) {
	var request PatchQuestionsQuestionIdRequestObject

	request.QuestionId = questionId

	var body PatchQuestionsQuestionIdJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PatchQuestionsQuestionId(ctx, request.(PatchQuestionsQuestionIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchQuestionsQuestionId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PatchQuestionsQuestionIdResponseObject); ok {
		if err := validResponse.VisitPatchQuestionsQuestionIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTopics operation middleware
func (sh *strictHandler) GetTopics(w http.ResponseWriter, r *http.Request) {
	var request GetTopicsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTopics(ctx, request.(GetTopicsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTopics")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetTopicsResponseObject); ok {
		if err := validResponse.VisitGetTopicsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostTopics operation middleware
func (sh *strictHandler) PostTopics(w http.ResponseWriter, r *http.Request) {
	var request PostTopicsRequestObject

	var body PostTopicsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostTopics(ctx, request.(PostTopicsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostTopics")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostTopicsResponseObject); ok {
		if err := validResponse.VisitPostTopicsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteTopicsTopicId operation middleware
func (sh *strictHandler) DeleteTopicsTopicId(w http.ResponseWriter, r *http.Request, topicId openapi_types.UUID) {
	var request DeleteTopicsTopicIdRequestObject

	request.TopicId = topicId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteTopicsTopicId(ctx, request.(DeleteTopicsTopicIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteTopicsTopicId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteTopicsTopicIdResponseObject); ok {
		if err := validResponse.VisitDeleteTopicsTopicIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PatchTopicsTopicId operation middleware
func (sh *strictHandler) PatchTopicsTopicId(w http.ResponseWriter, r *http.Request, topicId openapi_types.UUID) {
	var request PatchTopicsTopicIdRequestObject

	request.TopicId = topicId

	var body PatchTopicsTopicIdJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PatchTopicsTopicId(ctx, request.(PatchTopicsTopicIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchTopicsTopicId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PatchTopicsTopicIdResponseObject); ok {
		if err := validResponse.VisitPatchTopicsTopicIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FrZcxM5Gv9XVL1btVBl4s7FMN6XCcfMZheG4ITZB0iB3Ppsa6KWOjpCvJT/9y2p1e5LbTshNjDkKXG3",
	"9F36faf6c5SINBMcuFbR4HOkkimk2P17ZPR0CCoTXIH9nUmRgdQU3FucJKDUBy0ugNvfepZBNIiUlpRP",
	"onkvkjCWoKZLVhgF0r74u4RxNIj+1i9F6Xs5+m8VyIUQc0f20lAJJBq8q8vQ5Ojpn/cKxmL0JyTaMn4m",
	"AWt4Y0BpKvgQLu1/bRUJHY9pYpie2V/ATWqZAlazqBelQKhJo140xZJUuJTqwXXGMMeWRVB9kdlXjhPV",
	"kKpVpijkfe32HfPMOGVSfH2cbz/sRSnl5Q/PEUuJZ3alhmunZUr5S+ATPY0GuwG5tcho8oESu3QsZIp1",
	"NIiMoSRqLW6cx2Kn59WrmrBUuPtIziyB7vMAlUiaFQZN8XWhxmEcBxThOHXAhWucZsy+e4U1pFjTCxz1",
	"qvt37f6lZmlo6kiH9HghpZDdXgP2dftxIkhD0j+OXh4/Pzo7fv37hxfD4ethFNCPgMaU1QFUpzumwEgQ",
	"fFQpA4E384BOTRyloBSeNAQ+5leYUYKow+Uq+zmFS0ptSzbW53YLGfxfgNmyOKU01kZVHVhcWGDCRGIC",
	"znNLJdyrtkPQFJTGaVbzCII1PLKvQluuQCoP05J6vLO7E680jRe4yjak90sxod2hC1JMWZ37yBD6i/+5",
	"kwgbuha65MsDemRYqU9CkjoptZ8YuX/yi1IrtSkoLwh16CKM7lRmVSZpsKwvD/F7lcOuGzRBhIfA0WDd",
	"jedeVITv585ru3kngmtJR0YLuV4Q7kWJC57kA9brI/Rukxs3jOGRNZOWBgLr19Tky3JiWSh0J78vSXe9",
	"yGTkhpZuIMSRbRxxb93EWTvpmjDLAPeSKt0NN4I1vrG5GxgOmJvRlFbtTbmGCcg8pkwg/EYLjVnoVcOI",
	"TuZiuSdYsFxmiWrl1DIEVR8SIaXdUkowEoIB5k4jPIJGSD1qVBG9laXVOhVYQ9mc7wIYFTFXq9p97Gvi",
	"/ZZG6VR8Dee4mb7DPNhvL3cMYUKVtk3JhlNvu3p9aghFp5hrocTy+nXvdqm8QvGnvRrBJwGCUjCo5g6l",
	"DQGu6/GtXl+VS9Yor3vt4sEzDZ2Lbx06s+ptUmS937irHLeiLVnDRbx5KjqFLPLWpYctd7krjfTX6Ho7",
	"jP1F/etK0xXAuWnj2ha2OlS5E1e5q6BHG+Hp8DCGJwdx/Aj2fh49OtglB4/wT7uPHx0cPH58eHhwEMdx",
	"XCW8vs81gukto1svwiSlPOgZ7c4TJ5peWftRvvhXGZUBt51oL7L/2M3nN4kChS2dwL2yfVwaHax4kBhJ",
	"9ezUOlp+8iPAEuSRsUgqfv1amPbf/z2z5N1qe7zubWm5qdZZNLeEKR+LFtyj4YvTM3R0cozGQiI9BXT2",
	"n6MTCRnKGNb2/Hbe8/f8iDGEjZ4C1zSx4iPgJBOUa4W8AdBHK6CQ9H8u6AzQUycJem/ieD+pjgTdE/jo",
	"CJ8CoI8qg2QnJR8R5U4ECZlAUgi9EGpsGEOZFMQkGtnldGzloILvvOeuJ9cOPYXwRyfHUaXb9y2+C3PA",
	"cUajQbS/E+/suySmp87Kfatgn9n+3TmfyGOFdUHH6ZhEg+hEKG31dG1+lJ8+KP1UkFnRJFo0Dj5HOMuY",
	"l7H/p8pDSx48V4XW2ghhXseYDUHuQR4lnOB7cXxnvGvDZce7DhcnG1LGHefYMGvTg3j3zvjX53QBAYp5",
	"ViLB+j3FTDkZ9va2J8MfVgJHGeUDMOe3Jk2xnNlKu+IoCHOCJCRArwA59LvZDJ4oGy+cS5/b3QvwCd8D",
	"rUKfcNO8DcGvMvXZMv6aI6AwBCdAkMgLjq2C7y3HPsYBqQXraPCuHqbfnc/Pq5jwsLWIsPEsMVIC18j3",
	"Nai4GukCRp4lJxDAxG/gIPEKog0eS+O6p2WYZ14fo0DaOD2mDL6j0/kNdO1Y6qnOKvUPtVCr+5T8aa72",
	"X98db8iBG733N5ZBzlwQLJBvT+orZRAhEVxn1igNN6xH86HQ1mtrS1xUn4BGGHH4hPLiZqUTSz+iWAcf",
	"fuWmAFKflayFkN2tIcQGG+TL5EqpwWY5VH7eHlRe2BoeYSYBkxkqzs9j9huqOIoD9Xh0F+xBHE7drdyy",
	"XJLf220ylzRuBgPanoK8ogkgqlAu8Kyhb04CJVNILiqKns6UhtSreukHFGqZtm8Wi2wjIHEKGqRy+cJ2",
	"AdGlATkrerpBpADLZFq0Wzg4twzvrNwklHtXzjPCtGp3ECW1G46Iuqj7qX1Jl8AYG6aLOTpNLZtyoFG5",
	"DAgTzOf/QYp7sZsYeZJ+ZtLN4HyDqAzeygSweYInlLvIxKjSSIxRCbSvW/BY5vvbY/6rkCNKSJEv1y21",
	"rH1Lk6EHlalN381sHlYcunTP83lvSc6suvEmEmb4w6Qtp82uS7720RQriyT6wwLzm8jS63pGDjKEF95R",
	"cw4kOJt1+UYt3/U/F/8ek3kebhloaHvOc/d8QefNYldHMsywKwx8WL+sLq97wU1y3PnXHSbkNvihPSQ+",
	"2B7n391M13Cy9VJ+EROpsvUxQZQjjDIzYtR2oUjnEf0G/ppDp+av4hN3fvpPNGIiubBcxpZRnU13hltZ",
	"pv71fPQWWS3/vvLeZbfusjcdqV02TqyzsMM6mQYqO/v4W4D+3ReU4W8Atjypu4Xr+U/b7n3va6TL76eU",
	"zeEdTI3uSrdS1/YQ5vnDpd2frXDdDGXpOOcsX/GFPvMFH2LWv3ZqfX8Z+l4y8BFA+8rLjxq8BerDMPcS",
	"M1a8LQ3ozbG8d67YbFONc+3zmy13zY0TCd1HZDS575S/y07ZIR49cJGj1SAv0F/Gjv5n93etvjjffpav",
	"X6vk0Iu19+3wfX7/ttvhPOpRbnvhW7a96znf8ur+KzrZpor6mye7eNvJ7r6K/0G8/JngY0YTjR4QkzMB",
	"ZP3o4ffaT6yZ8B1teVWEkeb3YwlmiMAVMJGl+bfDRjL/reyg32d2wVQoPXgSP4n7OKP9q93ISuQ5NSn6",
	"62jMCVrEOMzKT2TL6OVvqOe9JonKN4PWRpYUThJhuEYp5ngCXlBPx5mpTSV373KDt9TDcqO3UXvrosUf",
	"YX5Ru3mo7H5Tueps8QallRNcgVL+Mq7gat917EESlGF+q4QrCp/KjcP8XWDrEPMLG80XS18CJiBHAksS",
	"WH5qMvAtZnlGFQmP3Ofi8/P5/wMAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
